/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.Aluno;
import classes.Publicacao;
import classes.Turma;
import classes.Usuario;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author ariel
 */
public class VisualizacaoAluno extends javax.swing.JFrame {

    int id;
    String nome;
    String email;
    String matricula;
    Turma t;

    public VisualizacaoAluno(Aluno a) {
        URL url = this.getClass().getResource("/images/logo.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
        id = a.getId_usuario();
        nome = a.getNome();
        email = a.getEmail();
        matricula = a.getMatricula();
        t = a.getTurma();
        initComponents();

    }

    private VisualizacaoAluno() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLLogo3 = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLMatricula = new javax.swing.JLabel();
        jLEmail = new javax.swing.JLabel();
        jButtonUpdateEmail = new javax.swing.JLabel();
        jButtonUpdateMatricula = new javax.swing.JLabel();
        jButtonUpdateTurma = new javax.swing.JLabel();
        jLTurma = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelPostagem = new javax.swing.JLabel();
        jLabelPostagemHeader = new javax.swing.JLabel();
        jLLocal21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDescricao = new javax.swing.JTextArea();
        jLabelPostagem3 = new javax.swing.JLabel();
        jLabelPostagem4 = new javax.swing.JLabel();
        jLabelFoto = new javax.swing.JLabel();
        jLSituacao = new javax.swing.JLabel();
        jLTitulo = new javax.swing.JLabel();
        jLLocal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(128, 0, 0));

        jLLogo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        jLNome.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLNome.setForeground(new java.awt.Color(255, 255, 255));
        jLNome.setText("Nome Usuario");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLNome, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLLogo3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLLogo3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNome, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 19)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(128, 0, 0));
        jLabel5.setText("Email:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 19)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 0, 0));
        jLabel7.setText("Matricula:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 19)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(128, 0, 0));
        jLabel8.setText("Turma:");

        jLMatricula.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLMatricula.setForeground(new java.awt.Color(128, 0, 0));

        jLEmail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLEmail.setForeground(new java.awt.Color(128, 0, 0));

        jButtonUpdateEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updateData.png"))); // NOI18N

        jButtonUpdateMatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updateData.png"))); // NOI18N

        jButtonUpdateTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updateData.png"))); // NOI18N

        jLTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLTurma.setForeground(new java.awt.Color(128, 0, 0));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPostagem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelPostagem.setForeground(new java.awt.Color(128, 0, 0));
        jLabelPostagem.setText("Título:");
        jPanel1.add(jLabelPostagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 60, -1));

        jLabelPostagemHeader.setFont(new java.awt.Font("Arial", 0, 19)); // NOI18N
        jLabelPostagemHeader.setForeground(new java.awt.Color(128, 0, 0));
        jLabelPostagemHeader.setText("Última postagem");
        jPanel1.add(jLabelPostagemHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, -1));

        jLLocal21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLLocal21.setForeground(new java.awt.Color(128, 0, 0));
        jLLocal21.setText("Local:");
        jPanel1.add(jLLocal21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 40, -1));

        jTDescricao.setEditable(false);
        jTDescricao.setColumns(20);
        jTDescricao.setRows(5);
        jTDescricao.setBorder(null);
        jScrollPane1.setViewportView(jTDescricao);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 109, 293, 84));

        jLabelPostagem3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelPostagem3.setForeground(new java.awt.Color(128, 0, 0));
        jLabelPostagem3.setText("Descrição:");
        jPanel1.add(jLabelPostagem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 88, 140, -1));

        jLabelPostagem4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelPostagem4.setForeground(new java.awt.Color(128, 0, 0));
        jLabelPostagem4.setText("Situação:");
        jPanel1.add(jLabelPostagem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 266, 70, -1));
        jPanel1.add(jLabelFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 299, 141, 127));

        jLSituacao.setText("as");
        jPanel1.add(jLSituacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 80, -1));

        jLTitulo.setText("jLabel2");
        jPanel1.add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLLocal.setText("as");
        jPanel1.add(jLLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 80, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonUpdateTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator5)
                                .addComponent(jSeparator4)
                                .addComponent(jSeparator3)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLMatricula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonUpdateEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonUpdateMatricula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(345, 345, 345))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButtonUpdateEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonUpdateMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel7)
                                .addGap(9, 9, 9)
                                .addComponent(jLMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonUpdateTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1016, 739));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jLNome.setText(nome);
        jLEmail.setText(email);
        jLMatricula.setText(matricula);
        jLTurma.setText(t.getNome());
        try {
            Cliente.out.writeObject("consultaPublicacoesUsuario");
            String resposta = (String) Cliente.in.readObject();
            Cliente.out.writeObject(id);
            if (resposta.equals("ok")) {
                Publicacao p = (Publicacao) Cliente.in.readObject();
                jLTitulo.setText(p.getTitulo());
                jTDescricao.setText(p.getDescricao());
                jLLocal.setText(p.getLocalLiteral());
                BufferedImage img;
                Image newimg;
                img = ImageIO.read(p.getArquivo());
                newimg = img.getScaledInstance(70, 70, java.awt.Image.SCALE_SMOOTH);
                ImageIcon icone = new ImageIcon(newimg);
                jLabelFoto.setIcon(icone);
                int situacao = p.getSituacao();
                int tipo = p.getTipo();
                if (situacao == 1) {
                    int confirmacao = p.getConfirmacao();
                    if (confirmacao == 1) {
                        jLSituacao.setText("Finalizado");
                    }
                    if (tipo == 1) {
                        jLSituacao.setText("Notificado. Não devolvido");
                    } else if (tipo == 0) {
                        jLSituacao.setText("Encontrado. Não devolvido");

                    }
                } else if (situacao == 0) {
                    jLSituacao.setText("Em andamento");
                }
            } else if (resposta.equals("vazio")) {
                jLTitulo.setVisible(false);
                jTDescricao.remove(this);
                jLLocal.setVisible(false);
                jLabelPostagem.setVisible(false);
                jLabelPostagem3.setVisible(false);
                jLLocal21.setVisible(false);
                jLabelPostagem4.setVisible(false);
                jLabelFoto.setVisible(false);
                jLabelPostagemHeader.setText("Nenhuma publicação");

            }
        } catch (IOException ex) {
            Logger.getLogger(VisualizacaoServidor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VisualizacaoServidor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizacaoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizacaoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizacaoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizacaoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizacaoAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jButtonUpdateEmail;
    private javax.swing.JLabel jButtonUpdateMatricula;
    private javax.swing.JLabel jButtonUpdateTurma;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLLocal;
    private javax.swing.JLabel jLLocal21;
    private javax.swing.JLabel jLLogo3;
    private javax.swing.JLabel jLMatricula;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLSituacao;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLTurma;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelPostagem;
    private javax.swing.JLabel jLabelPostagem3;
    private javax.swing.JLabel jLabelPostagem4;
    private javax.swing.JLabel jLabelPostagemHeader;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextArea jTDescricao;
    // End of variables declaration//GEN-END:variables
}
